name: receptify-gihub-actions

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Setup QEMU: Necessary to build ARM64 images on GitHub's Intel runners
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2. Setup Buildx: The engine that handles multi-arch builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Generate Docker Metadata (Tags)
      # This logic ensures that if you push tag 'v1.0.0', 
      # the image gets tagged as 'v1.0.0' AND 'latest'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jozsi01/receptify # REPLACE WITH YOUR IMAGE NAME
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      # 5. Build and Push
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          # IMPORTANT: Build for both standard PC and Raspberry Pi
          platforms: linux/amd64,linux/arm64
          push: true
          # Use the tags generated in the previous step
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}